replicaCount: 2

image:
  repository: docker.io/kavitha011/hello-world
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

containerPort: 8080

